version: '3'
services:
  kegbot:
    image: kegbot-server
    restart: always
    build: .
    ports:
      - "80:8000"
    volumes:
      - kegbot-data:/kegbot-data
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      KEGBOT_REDIS_URL: redis://redis:6379/0
      KEGBOT_DATABASE_URL: mysql://kegbot:password@172.17.0.1/kegbot
      KEGBOT_SETUP_ENABLED: "false"
      KEGBOT_DEBUG: "false"

  workers:
    image: kegbot-server
    restart: always
    command: bin/kegbot run_workers
    volumes:
      - kegbot-data:/kegbot-data
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      KEGBOT_REDIS_URL: redis://redis:6379/0
      KEGBOT_DATABASE_URL: mysql://kegbot:password@172.17.0.1/kegbot
      KEGBOT_SETUP_ENABLED: "false"
      KEGBOT_DEBUG: "false"

  # mysql:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_USER: 'kegbot'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_DATABASE: 'kegbot'
  #   tmpfs:
  #     - /tmp
  #     - /var/tmp
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always

volumes:
  # mysql-data:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /home/ubuntu/mysql-data
  kegbot-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/kegbot-data
